### PR TITLE
(MAINT) Standardise Windows Template Sub-Dirs

### PR DESCRIPTION
**Pull request by jcoconnor**
Adopt the "vmware/virtualbox" sub-directory structure across all the
windows builds. This leads to more standardised template files which
will allow further generalisation to a master template for the windows
builds.

It also facilitates adding virtualbox builds in a standard fashion to
the windows builds at a later date.

Also - set winrm timeout to 8hr across the board as slipstreaming and
other performance improvements have addressed this - i.e. no build takes
longer than about 2.5 hours.

### CODE REVIEW

**Comment by ScottGarman** [comment]
:+1:  Standardize all the things!

**Comment by glennsarti** [comment]
I am unable to verify all of the file changes, but given they're mostly renames...looks ok.

**Comment by jcoconnor** [comment]
Have run this through build testing on all platforms - Fixed an issue with the virtual box build.
Otherwise builds are ok.

**Comment by glennsarti** [comment]
Good enough for me.  LGTM

**Pull request merged**
