### PR TITLE
(IMAGES-498) Set EN_US local to UTF-8

### PR DESCRIPTION
**Pull request by jcoconnor**
Explicitly set the local to en_US.UTF-8 in the initial machine
configuration.

This PR also has MAINT refactor to use the AIO puppet configuration method.

### CODE REVIEW

**Comment by ScottGarman** [comment]
:+1:  since I'm aware that you built the base vm and verified the LOCALE was properly updated in /etc/default/locale.

**Comment by jcoconnor** [comment]
@ScottGarman  Need to replicate this for ```i386``` and also resolve output directory issues with second part of the build

**Comment by shrug** [comment]
Once this is merged I'll rebase https://github.com/puppetlabs/puppetlabs-packer/pull/184 - and it might make sense pull the AIO config work to the other debian/ubuntu platforms in #184 as well, since I'm touching those

**Comment by jcoconnor** [comment]
@MosesMendoza Yes - needs acceptance tested - has been discussed in ticket.

**Comment by jcoconnor** [comment]
Added open-vm-tools as suggested by @ScottGarman & @heathseals

**Comment by jcoconnor** [comment]
ping @puppetlabs/agent-team 
This PR is ready for merge.
Both images have been successfully deployed to ```vmpooler-dev``` and have passed Puppet Acceptance testing.

They have also been deployed to production.

**Comment by jcoconnor** [comment]
And re-opening as was accidentally closed.

**Comment by ScottGarman** [comment]
:+1:

**Comment by McdonaldSeanp** [comment]
I hate to nitpick on a variable name, but can we use the moniker puppet_agent instead of puppet_aio? I would like to start universally referring to the package as "puppet-agent" instead of the several terms we use like "aio" and "foss".

@jcoconnor that's likely out of scope for this PR, so I won't block on it, but I'd like to change that.

**Comment by McdonaldSeanp** [comment]
👍

**Pull request merged**
