### PR TITLE
disable systemd-resolved from ubuntu images >= 18.04

### PR DESCRIPTION
**Pull request by mihaibuzgau**

### CODE REVIEW

**Comment by ScottGarman** [comment]
I'm pretty sure we have other platforms in the pooler that use systemd-resolved - without checking, I'm guessing that's the case for SLES15 and recent Fedoras. If we're not seeing the same problems with those platforms it would be worth investigating further to find out why.

**Comment by mihaibuzgau** [comment]
@ScottGarman sles15 does not use systemd-resolved for DNS:
```
hqr4ts8i8lok4it:~ # cat /etc/*release
NAME="SLES"
VERSION="15"
VERSION_ID="15"
PRETTY_NAME="SUSE Linux Enterprise Server 15"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15"
hqr4ts8i8lok4it:~ # systemctl list-unit-files | grep resolv
hqr4ts8i8lok4it:~ #
```
Fedora 28 has the service disabled by default:
```
[root@bd1sp9iw6gmb63s ~]# cat /etc/*release
Fedora release 28 (Twenty Eight)
NAME=Fedora
VERSION="28 (Twenty Eight)"
ID=fedora
VERSION_ID=28
PLATFORM_ID="platform:f28"
PRETTY_NAME="Fedora 28 (Twenty Eight)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:28"
HOME_URL="https://fedoraproject.org/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=28
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=28
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
Fedora release 28 (Twenty Eight)
Fedora release 28 (Twenty Eight)
[root@bd1sp9iw6gmb63s ~]# systemctl list-unit-files | grep resolv
systemd-resolved.service                    disabled
```

Starting with Ubuntu 18.04 it's enabled by default:
```
root@v4mbguzyprveap8:~# cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

root@v4mbguzyprveap8:~# systemctl list-unit-files | grep resolv
dbus-org.freedesktop.resolve1.service         enabled
systemd-resolved.service                      enabled
```

If you've got any other ideas on how to investigate further I'll be happy to do the work.

**Comment by ScottGarman** [comment]
@mihaibuzgau ah, I misspoke then. I don't want to block this effort, so I'm :+1:

**Comment by mihaibuzgau** [comment]
@geoffnichols no, the fix does not work. For some reason if systemd-resoved is disabled the dhcp client does not setup the DNS servers on the box.
The easiest solution would be to leave systemd-resolved enabled and bypass it. Trying to figure out if there is a better solution.

**Comment by mihaibuzgau** [comment]
this is OK to merge now, the PE tests seem to be passing on the image that was built using this PR

**Pull request merged**
