### PR TITLE
(RE-7628) Add Resilience to Downloads

### PR DESCRIPTION
**Pull request by jcoconnor**
This PR includes and replaces #87 (RE-7519) IE Settings.
It includes the IE Settings and improvements as documented in https://github.com/puppetlabs/puppetlabs-packer/pull/87#issuecomment-235530945

This is to improve the download resiliency for:
1. Software download and installation
2. Accessing forgeapi.puppetlabs.com for module installation.
This is done by replacing chocolatey installs with downloads and installation commands.

This is particularly needed for the sysinternals utilities as they could be removed when chocolatey is removed (See [RE-7671](https://tickets.puppetlabs.com/browse/RE-7671)).

### CODE REVIEW

**Comment by McdonaldSeanp** [comment]
I like the use of downloads and installation commands myself, I'm not sure what you think @glennsarti but I couldn't find much wrong. I'll run a test build tonight to see how it goes.

**Comment by glennsarti** [comment]
:+1:  for merge pending @McdonaldSeanp doing a test build

**Comment by heathseals** [comment]
👍  this refactored PR builds for me.  only thing i noticed is that the VMware Tools cdrom is still present and attached post build.

**Comment by jcoconnor** [comment]
Tx @heathseals I have ticketed the VMWare tools issue as [RE-7681](https://tickets.puppetlabs.com/browse/RE-7681)

**Pull request merged**
