### PR TITLE
(WIP)(IMAGES-416) Add Win-2012R2 Base and Vagrant Templates to packer

### PR DESCRIPTION
**Pull request by jpogran**
This adds new files necessary to build virtualbox images with packer
using the work already done to build vmpooler images. It follows the
convention of adding new files for new builders instead of having one
parameterized build file.

### CODE REVIEW

**Comment by glennsarti** [comment]
Can't say I'm happy about the one builder per template scheme.  I'm having similar issues with the slipstreaming template too.

**Comment by jcoconnor** [comment]
@glennsarti Thats definitely a maint issue that we should deal with.

**Comment by jcoconnor** [comment]
@jpogran I'm going to take this one over under [IMAGES-416](https://tickets.puppetlabs.com/browse/IMAGES-416) in the next sprint.

**Comment by jcoconnor** [comment]
Closing as #156 includes this with any additional updates to build on the ```jenkins-imaging platform```

**Pull request closed without merging**
