### PR TITLE
(IMAGES-758) Add vsphere template for VRO 7.3 x86_64

### PR DESCRIPTION
**Pull request by ekinanp**
This is built from an existing OVA, downloaded here: https://my.vmware.com/web/vmware/details?productId=650&downloadGroup=VROVA_730#product_downloads

### CODE REVIEW

**Comment by ekinanp** [comment]
The VRO 7.3 template here was successfully deployed to the pooler, so this is ready for merge.

**Comment by ScottGarman** [comment]
Looks like it needs a README with instructions on how to build it - especially if it expects the OVA in a particular location.

**Comment by ekinanp** [comment]
@ScottGarman Thanks for the heads-up! I have added a README.

**Comment by ekinanp** [comment]
I pinged Jeremy to double check if the configure-for-vsphere.sh script looks OK. I don't know his GitHub username, so we should wait until he approves it before merging this.

**Comment by ScottGarman** [comment]
Readme looks good, I'm :+1: on this.

**Comment by geoffnichols** [comment]
Hi @ekinanp, I believe Jeremy is @jpadams on GitHub. I have requested his review!

**Comment by jpadams** [comment]
I've been trying to figure out if there was something else we could do to the image given that they've changed the auth scheme from local auth to requiring auth to a vRA or vSphere instance. Super annoying and doesn't seem to be a workaround. On brighter note, it _seems_ the API still works with built-in auth (vRO API is used by Beaker tests at moment).

**Pull request merged**
