### PR TITLE
adds vagrant libvirt, virtualbox and docker centos 7.3

### PR DESCRIPTION
**Pull request by witjoh**

### CODE REVIEW

**Comment by shrug** [comment]
ping @ScottGarman

**Comment by ScottGarman** [comment]
@witjoh I've been assuming you're doing this to add the latest CentOS releases (e.g, 6.9 in the other PR). I'm seeing that the latest CentOS 7 release is 7.4.1708, is there a reason you're not targeting that version?

**Comment by witjoh** [comment]
@ScottGarman The centos 7.4 is already merged in #276

**Comment by ScottGarman** [comment]
Oh, right - my confusion there.

**Comment by ScottGarman** [comment]
Given that this is a community-maintained platform, I'm thinking let's just have the iso_url point to a publicly accessible location for the ISO.

**Comment by witjoh** [comment]
I will add them to this PR

**Comment by mwaggett** [comment]
@ScottGarman @shrug wanna take another look?

**Comment by ScottGarman** [comment]
Looks good. :+1:

**Comment by witjoh** [comment]
thx for merging

**Pull request merged**
