### PR TITLE
WIP Centos6 redesign

### PR DESCRIPTION
**Pull request by witjoh**
@heathseals : first attempt. see the README.md.
comments welcome

### CODE REVIEW

**Comment by shrug** [comment]
ping @heathseals

**Comment by witjoh** [comment]
All images do build and initial vagrant up is working. Still working on 5.11, but get a 'not enough space found, creating the base image.

**Comment by underscorgan** [comment]
ping @heathseals

**Comment by melissa** [comment]
ping @heathseals @ScottGarman

**Comment by stahnma** [comment]
yo @heathseals review plz.

**Comment by witjoh** [comment]
Will have a look at the tests ...

**Comment by heathseals** [comment]
@witjoh i've fallen behind on reviewing PRs for this repo.  i hope to have a chance to take a look at this soon.

**Comment by witjoh** [comment]
Hope i didn't brake anything.  did a rebase

**Comment by stahnma** [comment]
It doesn't look like that rebase took, as there LOTS of commits in there you didn't make. Would you like to try again or do you need some help there?

**Comment by witjoh** [comment]
I will give it another try ..Will call for help if i mess it up again ...

**Comment by witjoh** [comment]
@heathseals @ScottGarman ....
This one can be closed ... 
replaced by #175

**Pull request closed without merging**
