### PR TITLE
(IMAGES-371) Add Windows 8.1 and 7. Packer Templates + Build perf improvements

### PR DESCRIPTION
**Pull request by jcoconnor**
This is a composite PR dealing with the following tickets
1. IMAGES-371 - Add Windows 8.1 builds to packer
2. IMAGES-370 - Add Windows 7 builds
3. IMAGES-379 - Use local VM Storage on build machine - also has JJB related changes
4. MAINT - Replace ```sdelete``` with more efficient disk zeroing operation.
5. IMAGES-369 - Further refinements to slipstreaming process in (1) and (2) above

### CODE REVIEW

**Comment by McdonaldSeanp** [comment]
All the work so far is 👍

**Comment by jcoconnor** [comment]
Ping @puppetlabs/agent-team This PR is ready for review.
The Windows 7 build needs further work due to issues with Windows updates, but the other fixes in this are important for all the builds (i.e. using local instead of NFS storage).

**Comment by jcoconnor** [comment]
Windows 7 build is working on local dev env and will be tested on Jenkins tonight.
So all the work in this ticket is complete pending review.

Onward testing:
1. Build on ```jenkins-imaging``` and export to vSphere - in progress
2. Deploy to ```vmpooler-dev``` - requires separate ticket to create pools.
3. Puppet Acceptance testing of 7 and 8.1 - ticket to be raised also.

**Comment by McdonaldSeanp** [comment]
👍

**Pull request merged**
