### PR TITLE
(RE-7519) IE Settings

### PR DESCRIPTION
**Pull request by jcoconnor**
Apply GPO settings to disable ability to change home page across all
users and set it to about:blank

### CODE REVIEW

**Comment by jcoconnor** [comment]
@glennsarti @Iristyle Have an interesting problem with setting these group policies.


If I use gpedit, I can clearly see the policy was applied and is visible under ```User Configuration\Administrative Templates\Windows Components\Internet Explorer```

However, the policy is not actually enforced - i.e. the browser home page is not restricted and I can change it in IE Settings.

Any suggestions ?
/cc @McdonaldSeanp

**Comment by jcoconnor** [comment]
@glennsarti I have merged in your changes and it almost works.
Had to remove one of the GUID's from the Default list - see https://github.com/puppetlabs/puppetlabs-packer/pull/87/commits/e371a50424032a516d375c51a5a7c1e805f2d651 for details.

/cc: @McdonaldSeanp

**Comment by jcoconnor** [comment]
Please hold of merging this until #89 is merged.

**Comment by jcoconnor** [comment]
@glennsarti @McdonaldSeanp This is ready for merge now.

As discussed:

1. I am just changing the default home page for current and default user rather than setting a GP to prevent it being changed.
2. However, the GP script changes @glennsarti added are still relevant, so keeping them in.
3. MAINT change included to separate puppet run into its own script - this is generic so belongs in scripts area - the registry and other changes can be a bit OS specific (e.g. UAC) so leaving those associated with the templates.

This appears to run ok on test, so recommend we merge today if possible.

**Comment by heathseals** [comment]
@jcoconnor i was able to rebuild the base without issue, but ran into some failures while building the cygwin configuration.  
```
 windows-2012r2-x86_64-vmware-vsphere-cygwin: Disabling Hibernation...
    windows-2012r2-x86_64-vmware-vsphere-cygwin: Found Modules directory C:\Packer\puppet\modules
    windows-2012r2-x86_64-vmware-vsphere-cygwin: Installing the puppetlabs-powershell module from the Forge...
    windows-2012r2-x86_64-vmware-vsphere-cygwin: % : The term 'C:\Program Files\Puppet Labs\Puppet\bin\puppet.bat' is not
    windows-2012r2-x86_64-vmware-vsphere-cygwin: recognized as the name of a cmdlet, function, script file, or operable
    windows-2012r2-x86_64-vmware-vsphere-cygwin: program. Check the spelling of the name, or if a path was included, verify
    windows-2012r2-x86_64-vmware-vsphere-cygwin: that the path is correct and try again.
    windows-2012r2-x86_64-vmware-vsphere-cygwin: At A:\puppet-configure.ps1:31 char:34
    windows-2012r2-x86_64-vmware-vsphere-cygwin: +   Get-Content -Path $ForgeMods | % {
    windows-2012r2-x86_64-vmware-vsphere-cygwin: +                                  ~~~
    windows-2012r2-x86_64-vmware-vsphere-cygwin: + CategoryInfo          : ObjectNotFound: (C:\Program File...\bin\puppet.b
    windows-2012r2-x86_64-vmware-vsphere-cygwin: at:String) [ForEach-Object], CommandNotFoundException
    windows-2012r2-x86_64-vmware-vsphere-cygwin: + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Co
    windows-2012r2-x86_64-vmware-vsphere-cygwin: mmands.ForEachObjectCommand
    windows-2012r2-x86_64-vmware-vsphere-cygwin:
==> windows-2012r2-x86_64-vmware-vsphere-cygwin: Restarting Machine
==> windows-2012r2-x86_64-vmware-vsphere-cygwin: Waiting for machine to restart...
    windows-2012r2-x86_64-vmware-vsphere-cygwin: WINPUPP-SCQ912Q restarted.
==> windows-2012r2-x86_64-vmware-vsphere-cygwin: Machine successfully restarted, moving on
==> windows-2012r2-x86_64-vmware-vsphere-cygwin: Provisioning with Powershell...
==> windows-2012r2-x86_64-vmware-vsphere-cygwin: Provisioning with shell script: /var/folders/4n/g5gtg6f11hl91yld8v_fhx780000gp/T/packer-powershell-provisioner181680818
    windows-2012r2-x86_64-vmware-vsphere-cygwin: Other Stuff.......
    windows-2012r2-x86_64-vmware-vsphere-cygwin: The operation completed successfully.
    windows-2012r2-x86_64-vmware-vsphere-cygwin: [WINPUPP-SCQ912Q]Boxstarter: Disabling UAC
    windows-2012r2-x86_64-vmware-vsphere-cygwin: [WINPUPP-SCQ912Q]Boxstarter: Enabling Remote Desktop...
    windows-2012r2-x86_64-vmware-vsphere-cygwin: [WINPUPP-SCQ912Q]Boxstarter: Disabling Remote Desktop NLA ...
    windows-2012r2-x86_64-vmware-vsphere-cygwin: The operation completed successfully.
    windows-2012r2-x86_64-vmware-vsphere-cygwin: The operation completed successfully.
    windows-2012r2-x86_64-vmware-vsphere-cygwin: The operation completed successfully.
==> windows-2012r2-x86_64-vmware-vsphere-cygwin: Restarting Machine
==> windows-2012r2-x86_64-vmware-vsphere-cygwin: Waiting for machine to restart...
    windows-2012r2-x86_64-vmware-vsphere-cygwin: WINPUPP-SCQ912Q restarted.
==> windows-2012r2-x86_64-vmware-vsphere-cygwin: Machine successfully restarted, moving on
==> windows-2012r2-x86_64-vmware-vsphere-cygwin: Provisioning with Powershell...
==> windows-2012r2-x86_64-vmware-vsphere-cygwin: Provisioning with shell script: /var/folders/4n/g5gtg6f11hl91yld8v_fhx780000gp/T/packer-powershell-provisioner367290985
    windows-2012r2-x86_64-vmware-vsphere-cygwin: Uninstalling Puppet Agent...
    windows-2012r2-x86_64-vmware-vsphere-cygwin: Uninstalling the following packages:
    windows-2012r2-x86_64-vmware-vsphere-cygwin: puppet-agent
    windows-2012r2-x86_64-vmware-vsphere-cygwin: puppet-agent is not installed. Cannot uninstall a non-existent package.
    windows-2012r2-x86_64-vmware-vsphere-cygwin:
    windows-2012r2-x86_64-vmware-vsphere-cygwin: Chocolatey uninstalled 0/1 packages. 1 packages failed.
    windows-2012r2-x86_64-vmware-vsphere-cygwin: See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
    windows-2012r2-x86_64-vmware-vsphere-cygwin:
    windows-2012r2-x86_64-vmware-vsphere-cygwin: Failures
    windows-2012r2-x86_64-vmware-vsphere-cygwin: - puppet-agent - puppet-agent is not installed. Cannot uninstall a non-existent package.
    windows-2012r2-x86_64-vmware-vsphere-cygwin: Uninstalling boxstarter...
    windows-2012r2-x86_64-vmware-vsphere-cygwin: Uninstalling the following packages:
    windows-2012r2-x86_64-vmware-vsphere-cygwin: boxstarter
    windows-2012r2-x86_64-vmware-vsphere-cygwin:
    windows-2012r2-x86_64-vmware-vsphere-cygwin: The system cannot find the file specified.
    windows-2012r2-x86_64-vmware-vsphere-cygwin: Boxstarter v2.8.29
    windows-2012r2-x86_64-vmware-vsphere-cygwin: Skipping auto uninstaller - No registry snapshot.
    windows-2012r2-x86_64-vmware-vsphere-cygwin: Boxstarter has been successfully uninstalled.
    windows-2012r2-x86_64-vmware-vsphere-cygwin:
    windows-2012r2-x86_64-vmware-vsphere-cygwin: Chocolatey uninstalled 1/1 packages. 0 packages failed.
    windows-2012r2-x86_64-vmware-vsphere-cygwin: See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
    windows-2012r2-x86_64-vmware-vsphere-cygwin: Removing page file.  Recreates on next boot
==> windows-2012r2-x86_64-vmware-vsphere-cygwin: Stopping virtual machine...
==> windows-2012r2-x86_64-vmware-vsphere-cygwin: Deleting output directory...
Build 'windows-2012r2-x86_64-vmware-vsphere-cygwin' errored: Script exited with non-zero exit status: 2. Allowed exit codes are: [0 1]
```

**Comment by jcoconnor** [comment]
Heath

I think the forge is down for a start.

**Comment by heathseals** [comment]
@jcoconnor forge seems to be working fine from here.
```
14:12 $ sudo puppet module install puppetlabs-motd
Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Notice: Installing -- do not interrupt ...
/etc/puppetlabs/code/environments/production/modules
└─┬ puppetlabs-motd (v1.4.0)
  └─┬ puppetlabs-registry (v1.1.3)
    └── puppetlabs-stdlib (v4.12.0)
```

**Comment by heathseals** [comment]
i ran the build again to see if it happened to be a transient error and noticed that the first error actually happened a bit earlier
```
    windows-2012r2-x86_64-vmware-vsphere-cygwin: Installing Puppet Agent...
    windows-2012r2-x86_64-vmware-vsphere-cygwin: Installing the following packages:
    windows-2012r2-x86_64-vmware-vsphere-cygwin: puppet-agent
    windows-2012r2-x86_64-vmware-vsphere-cygwin: By installing you accept licenses for the packages.
    windows-2012r2-x86_64-vmware-vsphere-cygwin: puppet-agent not installed. The package was not found with the source(s) listed.
    windows-2012r2-x86_64-vmware-vsphere-cygwin: If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
    windows-2012r2-x86_64-vmware-vsphere-cygwin: Version: ""
    windows-2012r2-x86_64-vmware-vsphere-cygwin: Source(s): "https://chocolatey.org/api/v2/"
    windows-2012r2-x86_64-vmware-vsphere-cygwin:
    windows-2012r2-x86_64-vmware-vsphere-cygwin: Chocolatey installed 0/1 packages. 1 packages failed.
    windows-2012r2-x86_64-vmware-vsphere-cygwin: See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
    windows-2012r2-x86_64-vmware-vsphere-cygwin:
    windows-2012r2-x86_64-vmware-vsphere-cygwin: Failures
    windows-2012r2-x86_64-vmware-vsphere-cygwin: - puppet-agent - puppet-agent not installed. The package was not found with the source(s) listed.
    windows-2012r2-x86_64-vmware-vsphere-cygwin: If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
    windows-2012r2-x86_64-vmware-vsphere-cygwin: Version: ""
    windows-2012r2-x86_64-vmware-vsphere-cygwin: Source(s): "https://chocolatey.org/api/v2/"
    windows-2012r2-x86_64-vmware-vsphere-cygwin: Installed Puppet Agent...
```

**Comment by jcoconnor** [comment]
@heathseals Its a too network sensitive which we need to address - I have created ticket [RE-7672](https://tickets.puppetlabs.com/browse/RE-7672).

Still puzzled at the first error you have logged though - I haven't seen it here (yet).

**Comment by jcoconnor** [comment]
@heathseals I have added a try/catch with loop to see if I can make the modules load more resilient.
It reattempts the download on failure up to a maximum number of attempts before bailing.

As noted earlier, will also add this on for the package installs.

/cc @glennsarti @McdonaldSeanp

**Comment by jcoconnor** [comment]
Closing as #92 replaces this PR.

**Pull request closed without merging**
