### PR TITLE
(REPLATS-467) Rebuild for 2021-10-06 PAM release

### PR DESCRIPTION
**Pull request by MikaelSmith**

### CODE REVIEW

**Review by jpartlow — APPROVED** [review]
Getting latest from beta :+1:

**Comment by MikaelSmith** [comment]
Pushed KOTS 1.52.1 to beta, so final build should pick that up.

**Comment by MikaelSmith** [comment]
Test install worked.

**Comment by MikaelSmith** [comment]
Final build: https://jenkins-sre.delivery.puppetlabs.net/view/imaging/view/Cent%20OS/job/imaging_centos-8.3-kurl-beta_x86_64_vmware_vcenter_packer_build_packer/57/

**Pull request merged**
