### PR TITLE
(IMAGES-48) Packer Windows-2012 Automation

### PR DESCRIPTION
**Pull request by jcoconnor**
Initial load of Win-2012 files for base win-2012 build.
This is mostly a copy of the win-2012r2 template with the following main changes:

1. DISM command for 2012 doesn't support /resetbase (leads to larger image unfortunately).
2. Initial image size needs to be 30GB

Remainder of template code appears to operate satisfactorily.

### CODE REVIEW

**Comment by jcoconnor** [comment]
This builds without issue using VMWare on Mac/Desktop.
Running it through a Jenkins build (which won't complete until tomorrow).

**Comment by McdonaldSeanp** [comment]
Nothing looks out of place 👍

**Comment by jcoconnor** [comment]
@glennsarti & @McdonaldSeanp The only significant difference I can see compared to win-2012 is that the DISM command doesn't support /ResetBase - this means that the generated image size if somewhat larger than that for Win-2012R2 :(

**Comment by jcoconnor** [comment]
@glennsarti & @McdonaldSeanp I have been able to deploy this template to the Dev Pooler without any issue, so this is ready for merge.

**Pull request merged**
