### PR TITLE
(IMAGES-447) Win-2016 Slipstream Automation 

### PR DESCRIPTION
**Pull request by jcoconnor**
Add in the automation files for Win-2016 slipstream generation.
The CU for Win-2016 updates has become a bit flaky, so regen the
slipstream to help this.

Also change all .Net 4.5.2 installs to use a more up to date chocolatey package.

### CODE REVIEW

**Comment by jcoconnor** [comment]
Have added in Windows-10 apps cleanup to this PR as it resolves the Win-10 sysprep issue [(IMAGES-503)](https://tickets.puppetlabs.com/browse/IMAGES-503).

Just running these through build and will confirm the acceptance test results shortly.

**Comment by jcoconnor** [comment]
Have verified that:

1. Windows-10 32 bit acceptance testing run completed successfully.
2. Windows-2016 is building and acceptance test run completes.
3. OneDrive and other Windows apps have been removed from Windows-10 images.

So this PR should be good to go pending review.

**Comment by ScottGarman** [comment]
:+1:

**Comment by jcoconnor** [comment]
Win-10 32 bit vmpooler is working fine, but 64 bit isn't - doing a rework of the app/package removal.

**Comment by jcoconnor** [comment]
@ScottGarman & @McdonaldSeanp Hit a blip on this as noted above with the 64 bit sysprep.
So went back and implemented a full app/package removal including provisioning.

This seems to have fixed the problem and it is building and starting up correctly for acceptance tests on both architectures now.

**Comment by McdonaldSeanp** [comment]
👍

**Pull request merged**
