### PR TITLE
(RE-9766) Update puppetlabs-packer to use artifactory

### PR DESCRIPTION
**Pull request by jennaesq**
This change updates references from using http://buildsources.delivery.puppetlabs.net/ to https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/.

### CODE REVIEW

**Comment by jennaesq** [comment]
sed is your friend;  once you realize BSD sed is installed on your mac, rather than GNU sed. (Mac growing pains)

**Comment by mwaggett** [comment]
Is there a higher level place this url could live, so future updaters would only have to update in one place? @shrug ?

**Comment by shrug** [comment]
Not the way the packer stuff is currently built, each of those files is an independent script, they don't template or source parent scripts. Everything could be refactored, but that's a bigger job. :)

**Comment by shrug** [comment]
ping @jcoconnor for review

**Comment by jcoconnor** [comment]
Going to merge this and add the equivalent to the ISO pulls in the windows variable files.

**Pull request merged**
