### PR TITLE
(IMAGES-22) Address DISM issues in Win-10 template

### PR DESCRIPTION
**Pull request by jcoconnor**
Use Slipstream image to prepare ISO with the latest CU available. This
reduces the overall install time, but may need to be updated prior to
each release to include the latest CU.

The DISM cleanup is done as part of the slipstream process so the
clean-dism script is not used for Windows-10 base build - at least until
bare-metal hardware is introduced as otherwise the jenkins-imaging
builds fail fairly consistently.

### CODE REVIEW

**Comment by jcoconnor** [comment]
@glennsarti & @McdonaldSeanp Ready for review.
Will need a final pass when I get my privs back to clone, i.e. test that the cloned instance moves to ready state, but worth pushing this lot up in the meantime.

Tx

**Comment by jcoconnor** [comment]
Ping @puppetlabs/agent-platform-team This PR is ready to merge.
The Win-10 image builds correctly and initialises on ```vmpooler-dev```

Currently running Puppet Acceptance tests and if these pass will deploy the image.

**Comment by ScottGarman** [comment]
:+1:

**Comment by LuvCurves** [comment]
👍

**Pull request merged**
