### PR TITLE
adds fedora 23 vagrant-libvirt templates

### PR DESCRIPTION
**Pull request by witjoh**
Added also a Vagrant template, which will be included in the box.  This solve my issues with the kernel oops during boot.  Solution : https://bugzilla.redhat.com/show_bug.cgi?id=1283989

### CODE REVIEW

**Comment by heathseals** [comment]
@witjoh any other tweaks required to remedy the panic on boot?  i seem to still be seeing that behavior with boxes built from this template.

**Comment by witjoh** [comment]
@heathseals : do you see it also on the fc23 and lower boxes ?  I still ave to add this tweak to the fc24 templates

**Comment by heathseals** [comment]
@witjoh let me run through the build again, but i'm pretty certain it was on fedora 23.

**Comment by witjoh** [comment]
@heathseals : whenever I use the following in my Vagrantfile : 
```
  config.vm.define "fedora" do |build|
    build.vm.box = "puppetlabs/fedora-23-x86_64-libvirt-nocm"
    build.vm.hostname = "fcbuild.koewacht.net"
    build.vm.provider :libvirt do |dom|
      dom.cpu_mode = 'host-passthrough'
      dom.memory = 16000
      dom.cpus   = 4
    end
  end
```
the box is booting properly.
When I use the following : 
```
  config.vm.define "fedora" do |build|
    build.vm.box = "puppetlabs/fedora-23-x86_64-libvirt-nocm"
    build.vm.hostname = "fcbuild.koewacht.net"
    build.vm.provider :libvirt do |dom|
      dom.cpu_mode = 'host-model'
      dom.memory = 16000
      dom.cpus   = 4
    end
  end
```
the box is hanging, caused by the kernel oop.
I check this setting using virt-manager after bringing up the box.
in the CPU section you get the following : 
host-model -> Copy host cpu configuration is ticked
host-passthrough -> this is displayed in the Model drop down

host is fc23 with following versions.
[johan@zbook build]$ rpm -qa | grep vagrant
vagrant-libvirt-0.0.32-1.fc23.noarch
vagrant-1.8.1-1.fc23.noarch

I should add some documentation about this issue.

**Comment by heathseals** [comment]
Got it.  If I add `cpu_mode = 'host-passthrough'` to my default Vagrantfile, it boots fine.  I expected that since `cpu_mode` is set within the Vagrantfile that's packaged with the box, it'd be merged with the options in my default Vagrantfile.  I guess it's not behaving in that manner.

**Comment by witjoh** [comment]
just tested it with a multi vm Vagrantfile.
Seems to work with me.  The  'cpu_mode = 'host-passthrough' from the box vagrant file is merged properly. I alsi tested with another box without a default Vagrantfile, and for that box the default is used : 'cpu_mode = 'host-model'   Anyway this must be documented :) Should thsi be done in the main README.md ? Or should this go somewhere else ?

**Comment by witjoh** [comment]
https://www.vagrantup.com/docs/vagrantfile/ somewhere at the end documents hoe the Vagrantfile is merged and where multiple Vagrantfile's are looked for

**Comment by heathseals** [comment]
@witjoh regarding docs for the libvirt peculiarities, maybe create a short libvirt writeup in docs/ ?  Otherwise, this looks good to me.

**Comment by stahnma** [comment]
@heathseals what are next steps here?

**Comment by heathseals** [comment]
we still need docs around some of the libvirt oddities, but i'm going to go ahead and merge this.

**Comment by witjoh** [comment]
Docs will come in a new PR - just been a bit too busy lately :)

**Pull request merged**
