### PR TITLE
sles-12 sp1 and sp2

### PR DESCRIPTION
**Pull request by shrug**
This adds SLES sp1 and sp2 support

### CODE REVIEW

**Comment by shrug** [comment]
This is still a WIP - the pooler customization script isn't working yet, the base build seems mostly ok, but may still need some tweaks.  The autoyast configs are ported almost straight over from Bento: https://github.com/chef/bento/tree/master/http/sles-12

**Comment by shrug** [comment]
the SP2 image seems to be working ok, I still need to port some changes over to SP1 and tidy up the commits

**Comment by stahnma** [comment]
👍

**Comment by shrug** [comment]
The vmpooler currently has a 'sles-12sp2-x86_64' pool running the result of this

**Comment by jcoconnor** [comment]
Can't comment on the SLES specific (XML) stuff, but the packer work looks fine.
👍

**Comment by ScottGarman** [comment]
LGTM

**Pull request merged**
