### PR TITLE
(IMAGES-116) Create i386 Windows-10 builds

### PR DESCRIPTION
**Pull request by jcoconnor**
Create the 32 bit build for Windows-10 Enterprise.
This is the primary (and only) 32 bit testing platform.

Also includes one vagrant related change based on #160.

### CODE REVIEW

**Comment by jcoconnor** [comment]
This is *almost* ready to go - need verification run on ```jenkins-imaging``` before we can merge, but useful to get comments from @puppetlabs/agent-platform-team

**Comment by jcoconnor** [comment]
@puppetlabs/agent-platform-team This PR is ready for merge.
I have successfully built the new image on ```jenkins-imaging``` and it is deployed to ```vmpooler-dev``` as ```win-10-ent-i386.pending```

**Comment by ScottGarman** [comment]
:+1:

**Comment by McdonaldSeanp** [comment]
👍

**Pull request merged**
