### PR TITLE
(MAINT) Use Packer vsphere-iso/clone plugins

### PR DESCRIPTION
**Pull request by jcoconnor**
Packer has not integrated the jetbrains vsphere-* plugins into its core
so switch over all vsphere builds to use this in favour of our local
versioned plugin.

This means the plugins can be removed from the builders.
One less thing to maintain - Yayyyyy

### CODE REVIEW

**Comment by jcoconnor** [comment]
Adding DNM - just need to check this builds before we say GO GO GO

**Comment by highb** [comment]
Once this is in, we should remember to remove the line about downloading the plugin from the docs https://confluence.puppetlabs.com/display/AGENT/Adding+new+vmpooler+image

**Comment by highb** [comment]
🤞 Hope these build with no issues.

**Comment by jcoconnor** [comment]
So it doesn't build because Packer on the build machines is 1.3.2

I will discuss with @puppetlabs/night-s-watch on Monday before making any changes.

**Pull request merged**
