### PR TITLE
Add vagrant-libvirt boxes and redesign using var-file for centos

### PR DESCRIPTION
**Pull request by witjoh**
Added centos 7.4 and 6.9
Updated to latest puppet-agent

### CODE REVIEW

**Comment by jcoconnor** [comment]
@shrug & @witjoh I am working on a  similar style PR for Windows - see #215 
We should perhaps try and standardise the variable naming for the files.

I see that Travis is failing to parse the variable files - I have a fix in the above PR for this.

**Comment by witjoh** [comment]
@shrug @jcoconnor Based on #215, I reorded the centos directory to following structure.  Is this how you intended to organise the windows files ?
Next step is to screen all used variables and list them up.  I also see a lot of ENV setting are used.  Should I do the same for simular vars ?

`
├── centos-6.6
│   ├── i386.vars.json
│   └── x86_64.vars.json
├── centos-6.7
│   ├── i386.vars.json
│   └── x86_64.vars.json
├── centos-6.8
│   ├── i386.vars.json
│   └── x86_64.vars.json
├── centos-6.9
│   ├── i386.vars.json
│   └── x86_64.vars.json
├── centos-7.0
│   └── x86_64.vars.json
├── centos-7.1
│   └── x86_64.vars.json
├── centos-7.2
│   └── x86_64.vars.json
├── centos-7.3
│   └── x86_64.vars.json
├── centos-7.4
│   └── x86_64.vars.json
└── centos-common
    ├── libvirt-base.json
    ├── libvirt-nocm.json
    ├── libvirt-puppet.json
    ├── virtualbox-base.json
    ├── virtualbox-nocm.json
    ├── virtualbox-puppet.json
    ├── vmware-base.json
    ├── vmware-nocm.json
    └── vmware-puppet.json
`

grts

**Comment by ScottGarman** [comment]
We're getting ready to do a big cleanup effort on the Linux templates. I'm :+1: to accepting this before we start making a bunch more changes.

**Comment by jcoconnor** [comment]
@witjoh I like the idea of a common file naming standard for the variable files, and since #215 is merged, it would be cool if we could stick with the ```ARCH.vars.json``` format.

I have also been discussing this with @ekinanp who has joined our team and is taking a look at this PR.

**Comment by ekinanp** [comment]
@witjoh Thank you for this PR. I am going to verify on my machine that all of these templates build for only the vmware base and vmware nocm templates before the other reviewers can double check this PR to ensure that it is correct. I have also talked with @jcoconnor, and we both agree that we can handle the naming convention of the templates internally on our end after this PR is merged in so you do not have to worry about that.

The reason I am only checking the vmware templates is b/c those are the ones we want to keep. Other templates, such as virtualbox or libvirt, can be restored via. version control when needed, so they should still remain as a part of this PR.

**Comment by mradcliffe** [comment]
> All other templates, such as virtualbox or libvirt, can be restored via version control when needed

Hi, as a clarifying question, does this mean that in future we should not depend on updates for puppetlabs packer builds for virtualbox or libvirt, and we should look elsewhere or maintain our own boxes? That's OK, and it's good to know now though I've been following this PR (and its predecessor) for awhile now.

**Comment by ekinanp** [comment]
@mradcliffe I am not sure, @jcoconnor or @ScottGarman would know more about that.

**Comment by ScottGarman** [comment]
Hi @mradcliffe. It's true, we're backing off on maintaining templates for platforms we're not using in our vmware/vSphere infrastructure. Nearly all of our templates are in bad shape, and we're applying our limited resources to fix and validate that particular subset. We didn't think it would serve the community to keep unmaintained templates around, so after this clean-up is done, you should feel free to use the remaining ones as a basis for other artifact types if it's helpful.

**Comment by mradcliffe** [comment]
Thanks, @ScottGarman. That's what I thought, and thanks for providing them until now. The builds have been a good resource.

**Comment by jcoconnor** [comment]
The ```Travis``` check failure is down to it trying to parse the new variable files as a full packer script. This is a non-breaking issue and will be resolved when the variable name files match for windows format.

**Comment by witjoh** [comment]
Sounds great.   I will follow this up closely, and think about the best approach for the future.  I would love to stick with the standards variables and keep the code as close as possible to this, How we provide the libvirt/virtualbox stuff to to public can be decided later.  I always have some templates in draft to build docker based boxes.  Could be interesting to the public also.
Curious where this leads ....

**Pull request merged**
