### PR TITLE
(RE-8033) Disable VMWare Tools Time Sync

### PR DESCRIPTION
**Pull request by jcoconnor**
The new Windows 2012R2 and Server 2016 packer templates have both
Windows Time synchronisation and Vmware Tools time synchronisation
enabled. This is usually a bad thing as you should really only have one
time source.

Disable the VMWare Tools Time sync (in both base and vshpere templates).
Use "FALSE" as we are building on VMWare Player (need to check that this
is properly set on exported vSphere host)

### CODE REVIEW

**Comment by jcoconnor** [comment]
@glennsarti I'm currently building these changes for testing, so please don't merge.
/cc @McdonaldSeanp

**Comment by glennsarti** [comment]
I'm not sure about the GMT -> PDT timezone change.  @heathseals Any comment?

**Comment by jcoconnor** [comment]
@glennsarti Its experimental for the start (need to push it up so that I can access the change on the build machine).

I noticed an irritating discontinuity in the event log that I'll discuss with you later today.

**Comment by heathseals** [comment]
@glennsarti we currently have a mix of GMT and PDT currently in the pooler, but i think it makes sense to standardize on GMT.

**Comment by jcoconnor** [comment]
@glennsarti & @heathseals As discussed, I have changed the TZ to UTC and also put in a time re-sync into the post-clone run once.

Will roll out Win-2016 builds first and will test tomorrow.

**Comment by glennsarti** [comment]
Verified the TZ name for the Unattend.XML as `UTC`

```
C> tzutil /l
...
(UTC-01:00) Azores                      
Azores Standard Time                    
                                        
(UTC-01:00) Cabo Verde Is.              
Cape Verde Standard Time                
                                        
(UTC) Coordinated Universal Time        
UTC                                     
                                        
(UTC+00:00) Casablanca                  
Morocco Standard Time                   
...
```

:+1:  for merge

**Comment by glennsarti** [comment]
As per @jcoconnor 's comment, I should've said UTC not GMT.

**Comment by jcoconnor** [comment]
@McdonaldSeanp @glennsarti Have tested the win-2016rtm-x86_64 and this appears to operate satisfactorily.
Its also a lot easier to see whats happening without the timezone flips.

```facter system_uptime``` returns the following:
```
PS C:\Users\Administrator> facter system_uptime
{
  days => 0,
  hours => 0,
  seconds => 1088,
  uptime => "0:18 hours"
}
PS C:\Users\Administrator>
```

**Comment by glennsarti** [comment]
LGTM

**Pull request merged**
