### PR TITLE
redesign using var-files - cleaned up the code and put it in one single commit.

### PR DESCRIPTION
**Pull request by witjoh**
cleaned up against latest upstream, updated to latest agent version, attemp to add virtualbox/vmware (not tested)
The other PR can be closed i believe.  Did messed up that one totally.

Also added the vware/virtualbox file, but those are not tested.

### CODE REVIEW

**Comment by stahnma** [comment]
@heathseals have a look?

**Comment by stahnma** [comment]
@witjoh it looks like the packer validate tests are not working. Any idea what's going on there?

**Comment by heathseals** [comment]
@stahnma i believe the tests pull in all json files and doesn't account for files containing variables only.  we'll probably need to update the tests to ignore those.

regarding the var files, i believe work has been ticketed to address some of the redundancies in our packer configs.  @jcoconnor, you may want to chime in here.

**Comment by witjoh** [comment]
@stahnma concerning testing, check the README.md. Working test is documented in there at the end.

**Comment by jcoconnor** [comment]
As @heathseals noted, we have some tickets in the [Packer/Scaleability and Enhancement Epic](https://tickets.puppetlabs.com/browse/IMAGES-458) to try and reduce the copy/pasta across the packer builds.

Wasn't aware that you could have separate variable files for packer.

**Comment by shrug** [comment]
Something is weird with a merge commit perhaps? Was this a merge or a rebase? It's showing a larger diff than I would expect.

**Comment by johan-open-future** [comment]
hmm, seems my rebase actions are always ending totally wrong .... will try to fix this the good way :)

**Comment by jcoconnor** [comment]
Thanks @johan-open-future - it looks good otherwise and I was intending to run it through tests against our build system in the next few weeks.

**Comment by witjoh** [comment]
@jcoconnor : that was the reason for the rebase ...  to try to add the testing and make it working ....

**Comment by shrug** [comment]
ping @jcoconnor were you able to test?

**Comment by jcoconnor** [comment]
@shrug Still on my todo list

**Comment by shrug** [comment]
I think there's still a bad rebase here?

**Comment by melissa** [comment]
Hey all! This PR seems to have been abandoned. I'm going to leave it open for another week, and if there's still no movement, I'm going to close it.

**Comment by witjoh** [comment]
I think I messed up the rebase again.  Maybe it is better to close this one.  It is easy to create a new PR with only the commits that matters.  I'm in holiday next week and will have time to clean this mess up.

Should I still keep centos 5 versions ?  This gives me always some troubles building it.  It always needs a manual shutdown succeed ? 
Will also add the newer versions.

**Comment by jcoconnor** [comment]
@witjoh It might be better to close it and start again to fix the issue.
As far as I can see we still need Centos 5 (and 4) - @ScottGarman can confirm on this.

**Comment by witjoh** [comment]
@jcoconnor OK, i will close this and start over, adding latest from 4 and 5, and also the new 6/7 releases.  Will open a new PR, a clean one this time.

**Pull request closed without merging**
