### PR TITLE
adds vagrant libvirt, virtualbox and docker centos 6.9

### PR DESCRIPTION
**Pull request by witjoh**

### CODE REVIEW

**Comment by ScottGarman** [comment]
Thanks for this. I'll need to mirror the ISO and do a test build, hopefully later this week.

**Comment by ScottGarman** [comment]
Given that this is a community-maintained platform, I'm thinking let's just have the iso_url point to a publicly accessible location for the ISO.

**Comment by witjoh** [comment]
hmmm ... i did an update of my master branch with yours, than a git rebase master in this branch ... I wouldn't expect to see your commits ..... Doing something wrong again :(

**Comment by witjoh** [comment]
Weird thing is that my branch only show 4 files caned against update master ... bit in the PR it shows 64 files ...

**Comment by witjoh** [comment]
Cleaned this PR ...

**Comment by ScottGarman** [comment]
Looks good. :+1:

**Comment by witjoh** [comment]
Thx for merging

**Pull request merged**
