### PR TITLE
(IMAGES-7832) Add Win-2008R2 Base and Cygwin Templates to packer

### PR DESCRIPTION
**Pull request by jcoconnor**
The files and procedures needed to create the Win-2008r2 template for
packer.

Note - some incompatible scripts (e.g. disk sizing) have been exluded in
this commit and will be handled later.

Modifications were also required to the Policy editor script to handle
PS Version 2

### CODE REVIEW

**Comment by jcoconnor** [comment]
Hi @glennsarti This works very nicely - thanks for the addition.
Builds successfully on my desktop, so going to pump the build through the Jenkins pipeline.
This will take a few hours, but if it builds and deploys ok to vSphere, we should be good to merge this PR.

Still need to get the cleanup sorted, but will work on separate PR for that.

**Comment by jcoconnor** [comment]
@McdonaldSeanp Can you take a peek at this PR too please?

**Comment by glennsarti** [comment]
Is this still a WIP PR?

**Comment by jcoconnor** [comment]
@glennsarti Can be merged subject to review.

**Comment by glennsarti** [comment]
I'm 👍 for merge

**Pull request merged**
