### PR TITLE
(IMAGES-345) Debian 9.0 alpha templates

### PR DESCRIPTION
**Pull request by ScottGarman**
This is based on the Debian 9 alpha 8 installer release from 2016-11-12.

### CODE REVIEW

**Comment by ScottGarman** [comment]
Ping @heathseals just want to check w/ you that it's okay to call this template debian-9.0, since it's for an alpha release. Let me know if pre-releases need to be versioned differently. Otherwise I assume we just update the template files with the new installer ISOs once the release is out.

**Comment by stahnma** [comment]
Does it build?

**Comment by ScottGarman** [comment]
Yes, build-tested.

**Comment by stahnma** [comment]
👍

**Comment by heathseals** [comment]
@ScottGarman i've added a couple commits here https://github.com/ScottGarman/puppetlabs-packer/compare/debian-9...heathseals:ScottGarman-debian-9.  it fixes a couple typos and addresses a few items in the templates that were not part of the templates you used as a reference.  it also switches the ethernet adapter used on the artifact we ship to vsphere from e1000 to vmxnet3.  with these changes i got a good [build](https://jenkins-imaging.delivery.puppetlabs.net/view/Dynamic/job/Dynamic%20Base%20Image%20Builder/27/) and [ship](https://jenkins-imaging.delivery.puppetlabs.net/view/Dynamic/job/Dynamic%20Ship%20to%20vSphere/14/).

**Comment by ScottGarman** [comment]
After checking with Heath, I've rebased his fixup commits into this PR. So this should be ready for merge.

**Pull request merged**
